#!/bin/bash
#
# API E2E Test Generator
#
# Automatically generates E2E tests for all API endpoints.
# Validates response structure for every endpoint.
#
# Usage:
#   bash scripts/generate-api-e2e-tests.sh
#

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

OUTPUT_DIR="apps/web/tests/e2e/api-validation"
LAMBDA_DIR="infrastructure/lambda"

echo ""
echo -e "${BLUE}🔧 Generating API E2E Tests...${NC}"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# ============================================================
# Discover all API endpoints from Lambda functions
# ============================================================
echo "Discovering API endpoints..."

ENDPOINTS=()
ENDPOINT_HANDLERS=()

# Find all Lambda handler index.ts files (excluding shared/)
while IFS= read -r handler; do
  # Extract endpoint path from directory structure
  # Example: infrastructure/lambda/scenarios/list/index.ts -> /scenarios (LIST)
  dir=$(dirname "$handler")
  relative_path=${dir#infrastructure/lambda/}

  # Skip shared modules
  if [[ "$relative_path" == shared* ]]; then
    continue
  fi

  # Parse endpoint name
  IFS='/' read -ra PARTS <<< "$relative_path"
  resource="${PARTS[0]}"
  action="${PARTS[1]:-list}"

  # Map action to HTTP method
  case "$action" in
    list|get)
      method="GET"
      ;;
    create)
      method="POST"
      ;;
    update)
      method="PUT"
      ;;
    delete)
      method="DELETE"
      ;;
    *)
      method="GET"
      ;;
  esac

  # Build endpoint path
  if [ "$action" = "list" ]; then
    endpoint="/$resource"
  elif [ "$action" = "get" ]; then
    endpoint="/$resource/:id"
  else
    endpoint="/$resource"
  fi

  ENDPOINTS+=("$method $endpoint")
  ENDPOINT_HANDLERS+=("$handler")

  echo "  Found: $method $endpoint"
done < <(find "$LAMBDA_DIR" -name "index.ts" -type f)

echo ""
echo "Total endpoints discovered: ${#ENDPOINTS[@]}"
echo ""

# ============================================================
# Generate test file
# ============================================================
echo "Generating test file..."

cat > "$OUTPUT_DIR/api-response-structure.spec.ts" << 'EOF'
/**
 * Automated API Response Structure Tests
 *
 * AUTO-GENERATED: Do not edit manually
 * Generated by: scripts/generate-api-e2e-tests.sh
 *
 * Validates that ALL API endpoints return standard response structure:
 * - Success: { success: true, data: {...} }
 * - Error: { success: false, error: { code, message } }
 */

import { test, expect } from '@playwright/test';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api/v1';

// Helper: Login and get token
async function getAuthToken(page: any): Promise<string> {
  await page.goto('/login');
  await page.fill('input[name="email"]', 'admin@prance.com');
  await page.fill('input[name="password"]', 'Admin2026!Prance');
  await page.click('button[type="submit"]');
  await page.waitForURL('/dashboard', { timeout: 10000 });

  const token = await page.evaluate(() => localStorage.getItem('accessToken'));
  if (!token) {
    throw new Error('Failed to get access token');
  }

  return token;
}

// Helper: Validate response structure
function validateResponseStructure(response: any, endpoint: string) {
  const keys = Object.keys(response);

  // Must have 'success' field
  expect(keys).toContain('success');
  expect(typeof response.success).toBe('boolean');

  if (response.success === true) {
    // Success response must have 'data' field
    expect(keys).toContain('data');
    expect(response.data).toBeDefined();

    // Must NOT have 'error' field
    expect(keys).not.toContain('error');
  } else {
    // Error response must have 'error' field
    expect(keys).toContain('error');
    expect(response.error).toBeDefined();
    expect(response.error).toHaveProperty('code');
    expect(response.error).toHaveProperty('message');

    // Must NOT have 'data' field
    expect(keys).not.toContain('data');
  }

  console.log(`✅ ${endpoint}: Response structure valid`);
}

test.describe('API Response Structure Validation', () => {
  let authToken: string;

  test.beforeAll(async ({ browser }) => {
    const page = await browser.newPage();
    authToken = await getAuthToken(page);
    await page.close();
  });
EOF

# Generate test cases for each endpoint
for i in "${!ENDPOINTS[@]}"; do
  endpoint="${ENDPOINTS[$i]}"
  method=$(echo "$endpoint" | cut -d' ' -f1)
  path=$(echo "$endpoint" | cut -d' ' -f2)

  # Skip endpoints that require specific IDs (for now)
  if [[ "$path" == *":id"* ]]; then
    continue
  fi

  cat >> "$OUTPUT_DIR/api-response-structure.spec.ts" << EOF

  test('$method $path - response structure', async ({ request }) => {
    const response = await request.$method('${API_BASE_URL}${path}', {
      headers: {
        'Authorization': \`Bearer \${authToken}\`,
        'Content-Type': 'application/json',
      },
    });

    const data = await response.json();
    validateResponseStructure(data, '$method $path');
  });
EOF
done

# Close test file
cat >> "$OUTPUT_DIR/api-response-structure.spec.ts" << 'EOF'
});
EOF

echo -e "${GREEN}✅ Test file generated: $OUTPUT_DIR/api-response-structure.spec.ts${NC}"
echo ""
echo "Run tests:"
echo "  npm run test:e2e -- api-validation/"
echo ""
